### ISSUE TITLE
Docs: ASP.NET Core WebAPI example(s)

### ISSUE THREAD

**Issue by cliff-wakefield-acurus** [aws-powertools/powertools-lambda-dotnet#220]
### What were you searching in the docs?

Example of how to make use of PowerTools within a C# project created using the serverless.AspNetCoreWebAPI template.

In this template there is no handler method as everything is done through a Lambda Entry Point which is a sub-class of Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction.

### How can we improve?

```markdown
Provide more examples, or templates that make use of PowerTools.
```

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by swimming-potato** [comment]
Hi, I will take this one as a starter :)

**Comment by mungojam** [comment]
It's probably worth highlighting that web APIs can be hosted using the top level program approach as well. You no longer need to subclass Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction unless you want to override some default behaviour
