### ISSUE TITLE
Feature: Automatic Register XRay for all services

### ISSUE THREAD

**Issue by hjgraca** [aws-powertools/powertools-lambda-dotnet#249]
### Use case

When your application makes calls to AWS services to store data, write to a queue, or send notifications, the X-Ray SDK for .NET tracks the calls downstream in [subsegments](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-dotnet-subsegments.html). Traced AWS services and resources that you access within those services (for example, an Amazon S3 bucket or Amazon SQS queue), appear as downstream nodes on the service map in the X-Ray console.

Currently a user has to explicitly enable all of AWS SDK for .NET clients by calling `AWSSDKHandler.RegisterXRayForAllServices();` 

``` csharp
    public Functions()
    {
#if !DEBUG
        AWSSDKHandler.RegisterXRayForAllServices();
#endif
    }
```
The user might forget to do that and fail to get full advantage of tracing between Lambda and Downstream AWS services.
This is also error prone when developing locally and needs to be wrapped in a preprocessor directive `#if !DEBUG` to avoid exceptions

### Solution/User Experience

We could implement this functionality in our tracing utility in two different ways

1. Have it enabled by default for all services, and if the user does not want it will have to explicitly disable it. The common use case is when the user wants to instrument clients for some services and not others. The user would call `RegisterXRay` instead of `RegisterXRayForAllServices`
	``` csharp
	AWSSDKHandler.RegisterXRay<IAmazonDynamoDB>()
	```
2. Disabled by default and the user has to explicitly enable the feature.

Examples:

1. The feature is enabled by default, all tracing is done and configured by Powertools
``` csharp
  [Tracing(CaptureMode = TracingCaptureMode.ResponseAndError)]
  public async Task<APIGatewayProxyResponse> Get(APIGatewayProxyRequest request, ILambdaContext context)
  {
      var response = new APIGatewayProxyResponse
      {
          StatusCode = (int)HttpStatusCode.OK,
          Body = "Hello",
          Headers = new Dictionary<string, string> { { "Content-Type", "text/plain" } }
      };

      return response;
  }
```

The user can disable it explicitly by setting `RegisterXRayForAllServices` to `false` in the Tracing attribute or Environment Variable 
``` csharp
  [Tracing(CaptureMode = TracingCaptureMode.ResponseAndError, RegisterXRayForAllServices = false)]
  public async Task<APIGatewayProxyResponse> Get(APIGatewayProxyRequest request, ILambdaContext context)
  {
	  // have to explicitly register all services
	  AWSSDKHandler.RegisterXRayForAllServices();
      // or single service
	  AWSSDKHandler.RegisterXRay<IAmazonDynamoDB>()

      var response = new APIGatewayProxyResponse
      {
          StatusCode = (int)HttpStatusCode.OK,
          Body = "Hello",
          Headers = new Dictionary<string, string> { { "Content-Type", "text/plain" } }
      };

      return response;
  }
```

2. Disabled by default, have to explicitly enable it by setting `RegisterXRayForAllServices` to `true` in the Tracing attribute or Environment Variable 
``` csharp
  [Tracing(CaptureMode = TracingCaptureMode.ResponseAndError, RegisterXRayForAllServices = true)]
  public async Task<APIGatewayProxyResponse> Get(APIGatewayProxyRequest request, ILambdaContext context)
  {
      var response = new APIGatewayProxyResponse
      {
          StatusCode = (int)HttpStatusCode.OK,
          Body = "Hello",
          Headers = new Dictionary<string, string> { { "Content-Type", "text/plain" } }
      };

      return response;
  }
```

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-dotnet/tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by amirkaws** [comment]
According to the documentation [Tracing AWS SDK calls with the X-Ray SDK for .NET](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-dotnet-sdkclients.html) we can instrument all of your AWS SDK for .NET clients by calling RegisterXRayForAllServices before you create them. if we add the RegisterXRayForAllServices to the Tracing attribute it will be executed after constructor when function handler is being invoked, and all of the service clients which are instantiated in constructor won't be instrumented. So I suggest wrapping the functionalities in Tracing static class instead.  

```csharp
public Functions()
{
       // have to explicitly register all services
	  Tracing.RegisterForAllServices();
      // or single service
	  Tracing.RegisterForService<IAmazonDynamoDB>()
}
```
