### ISSUE TITLE
Bug: [Trace] attribute hides stacktrance

### ISSUE THREAD

**Issue by jaknor** [aws-powertools/powertools-lambda-dotnet#353]
### Expected Behaviour

Not sure if I am missing something, but I would expect that when an exception is thrown inside a method which is marked with the [Trace] attribute I should see the full stack trace for that exception

### Current Behaviour

The stack trace shows this instead of the actual location of the error

Stack Trace: 
    TracingAspectHandler.OnException[T](AspectEventArgs eventArgs, Exception exception)
    MethodAspectAttribute.WrapAsync[T](Func`2 target, Object[] args, AspectEventArgs eventArgs)
    <MyExecutingMethod> line 154

### Code snippet

```csharp
Please see this repo
https://github.com/jaknor/aws-lambda-powertools-tracing-stack-trace-bug/blob/main/README.md

Note, I've only reproduced it in unit test here, but we have seen the same behaviour when deployed to a Lambda.
```

### Steps to Reproduce

Please see repo https://github.com/jaknor/aws-lambda-powertools-tracing-stack-trace-bug/blob/main/README.md

### Powertools for AWS Lambda (.NET) version

latest

### AWS Lambda function runtime

dotnet6

**Comment by hjgraca** [comment]
Hi @jaknor thanks for opening an issue and the detailed repro and images.
We have some work in progress, not all utilities to bubble up the full stack trace.
We will track the work in this issue and update when we have made progress.

**Comment by hjgraca** [comment]
Hi @jaknor thanks again for reporting this issue and for the sample project. 
Pull request in progress #357

**Comment by hjgraca** [comment]
Hi @jaknor thank you for your support of the project. A fix for this issue will be released in the next release. #357

**Comment by jaknor** [comment]
Thanks! Will keep an eye out for the release
