### ISSUE TITLE
Feature request: custom log formatter 

### ISSUE THREAD

**Issue by sliedig** [aws-powertools/powertools-lambda-dotnet#366]
### Use case

Allow customers to bring their own custom log formatter for logging

### Solution/User Experience

Provide functionality similar to Python and Typescript implementations. 

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (.NET) Tenets](https://docs.powertools.aws.dev/lambda/dotnet/tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/)

**Comment by hjgraca** [comment]
release version 1.4.2
