### ISSUE TITLE
Maintenance: Replace Moq library

### ISSUE THREAD

**Issue by amirkaws** [aws-powertools/powertools-lambda-dotnet#369]
### Summary

Moq included [SponsorLink](https://github.com/devlooped/SponsorLink) from [version 4.20](https://github.com/moq/moq/releases/tag/v4.20.0). A [privacy issue](https://github.com/moq/moq/issues/1372) has been raised. 

from a privacy standpoint we should consider to moving away from Moq to another library such as [NSubstitute](https://nsubstitute.github.io/).

### Why is this needed?

Avoid sending data to 3rd parties.  

### Which area does this relate to?

Tests

### Solution

Replace [Moq](https://www.nuget.org/packages/Moq) dependencies with [NSubstitute](https://www.nuget.org/packages/NSubstitute) NuGet packages and refactor all unit tests to use new library instead.

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (.NET) Tenets](https://docs.powertools.aws.dev/lambda/dotnet/#tenets)

**Comment by hjgraca** [comment]
release in version 1.4.2
