### ISSUE TITLE
Tracing for RDS/MySQL

### ISSUE THREAD

**Issue by ssathasivan** [aws-powertools/powertools-lambda-dotnet#436]
### Use case

Our .NET Applications use MySQL as the relational database. It did not find support for tracing MySQL. It only supports SQL Server. Is there a plan for tracing MySQL queries in the pipeline.

### Solution/User Experience

Support for tracing MySQL

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (.NET) Tenets](https://docs.powertools.aws.dev/lambda/dotnet/tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/)

**Comment by hjgraca** [comment]
Hi @ssathasivan that functionality is part of X-Ray SDK for .NET. Currently the SDK [only supports](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-dotnet-sqlqueries.html) SQL Server like you mentioned. I would recommend opening an issue on the [AWS SDK for .NET repository](https://github.com/aws/aws-sdk-net).
Hope you can find your answer there.

**Comment by hjgraca** [comment]
Closing issue.
