### ISSUE TITLE
Docs: update community section with videos and workshops

### ISSUE THREAD

**Issue by sliedig** [aws-powertools/powertools-lambda-dotnet#535]
### What were you searching in the docs?

Community video and workshops for learning Powertools

### Is this related to an existing documentation section?

https://docs.powertools.aws.dev/lambda/dotnet/we_made_this/

### How can we improve?

```markdown
Add community videos and workshops
```

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by hjgraca** [comment]
#536 closed
