### ISSUE TITLE
Maintenance: Release 1.9.0

### ISSUE THREAD

**Issue by amirkaws** [aws-powertools/powertools-lambda-dotnet#562]
### Summary

Release 1.9.0

- Add AppConfig parameter provider feature
- Update NuGet packages to the latest

### Why is this needed?

Release

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (.NET) Tenets](https://docs.powertools.aws.dev/lambda/dotnet/#tenets)

**Comment by amirkaws** [comment]
Released [1.9.0](https://github.com/aws-powertools/powertools-lambda-dotnet/releases/tag/1.9.0)

**Comment by hjgraca** [comment]
cc @aviv-akhansari. AppConfig provider now available in version 1.3.0 of Parameters. Give it a try and if you have any feedback let us know. Thanks
