### ISSUE TITLE
Feature request: Reduce use of lesser known packages in Idemopotency package

### ISSUE THREAD

**Issue by mungojam** [aws-powertools/powertools-lambda-dotnet#568]
### Use case

We have to be careful with the dependencies that we bring in. The Idempotency package brings in a JmesPath package which then brings in other sub-packages. The sub-packages are particularly obscure, developed as a university project with very few users. https://www.nuget.org/packages/Springcomp.GPPG.Runtime

We would like the JmesPath package dependency to be replaced with native System.Text.Json functionality, or else a more widely used package (e.g. Newtonsoft.Json).

Otherwise I don't think we will be able to make use of the Idempotency package.

### Solution/User Experience

It seems that the main use is here, and could be replaced with a System.Text.Json use:

https://github.com/aws-powertools/powertools-lambda-dotnet/blob/develop/libraries/src/AWS.Lambda.Powertools.Idempotency/Serialization/JsonFunction.cs

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (.NET) Tenets](https://docs.powertools.aws.dev/lambda/dotnet/tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/)

**Comment by hjgraca** [comment]
Hi @mungojam just to give you an update: PR created #578

**Comment by hjgraca** [comment]
@mungojam [Release 1.10.0](https://github.com/aws-powertools/powertools-lambda-dotnet/releases/tag/1.10.0) removes dependency on 3rd party JMESPath. Using [Idempotency 1.2.1](https://www.nuget.org/packages/AWS.Lambda.Powertools.Idempotency/1.2.1) will not have that external dependency.
Hope you find it useful and reach out if you have any other questions or suggestions.
Thanks
