### ISSUE TITLE
Feature request: Sign the assemblies in the PowerTools packages.

### ISSUE THREAD

**Issue by ddoti** [aws-powertools/powertools-lambda-dotnet#597]
### Use case

We are building libraries that leverage some of the AWS Powertools packages to help with the transition to AWS. As part of our best practices, our libraries are signed to ensure they are cannot be tampered by an outside party. We have other protections to help prevent us from pulling down packages from an untrusted source. However, signing the assembly just adds that additional layer of protection.

### Solution/User Experience

The solution to this would be to sign the assemblies that are published in the AWS Powertools packages.

https://learn.microsoft.com/en-us/visualstudio/ide/managing-assembly-and-manifest-signing?view=vs-2022

Anything that was referencing packages with unsigned assemblies will not break when upgrading to assemblies that are signed.

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (.NET) Tenets](https://docs.powertools.aws.dev/lambda/dotnet/tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/)

**Comment by hjgraca** [comment]
Hey @ddoti thanks for raising the issue.
We do in fact sign all our DLLs as you can see from the image bellow when opening the Logging DLL

<img width="442" alt="image" src="https://github.com/aws-powertools/powertools-lambda-dotnet/assets/999396/2e7892e7-ca18-4fd9-a7a1-6adc761bc502">

**Comment by ddoti** [comment]
When packaging my library, or when packaging a signed lambda I get the following warnings:
```
... publish: CSC : warning CS8002: Referenced assembly 'AWS.Lambda.Powertools.Tracing, Version=1.4.2.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
... publish: CSC : warning CS8002: Referenced assembly 'AWS.Lambda.Powertools.Logging, Version=1.5.1.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
... publish: CSC : warning CS8002: Referenced assembly 'AWS.Lambda.Powertools.Metrics, Version=1.6.1.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
```
Which then fails when it is signing the top level assembly. I would assume that if these assemblies were being signed it would have a PublicKeyToken that would be used for validating the assembly isn't tampered with.

**Comment by hjgraca** [comment]
Hey @ddoti thanks for providing more info.
Let me refer back to the .NET documentation and why we only sign the DLLs but do not create strong naming. https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming

Let me point out some quotes from the docs:

> Strong naming has no benefits on .NET Core/5+. C# compiler produces CS8002 warning for strong-named assemblies referencing non-strong named assemblies. It is fine to suppress this warning for libraries that target .NET Core/5+ only.

We are only targeting .NET 6 and .NET 8, strong naming is recommended only on previous versions or full .NET framework.
It is safe to supres that warning.

> You should strong name your open-source .NET libraries if their targets include .NET Framework or .NET Standard. **Strong naming is not required for libraries that target .NET Core/5+ only.**

Contrary opinion contested by the .NET team on this issue https://github.com/dotnet/docs/issues/22412

> We saw strong naming creating many problems, and having diminishing value in .NET Core. We wanted problems with strong naming to go away in .NET Core. Ignoring strong names for binding was a part of the plan to achieve that.

Hope this helps
