### ISSUE TITLE
Feature request: Ability to not throw error on full batch failure

### ISSUE THREAD

**Issue by hjgraca** [aws-powertools/powertools-lambda-dotnet#608]
### Use case

Currently when using the Batch Processor utility, if all the records in a batch are marked as failed the utility throws a `BatchProcessingException`.

Taking into consideration that the utility is supposed to be used with partial failure reporting, a Lambda function that throws an error is functionally equal to a partial failure that reports all items as failed in the sense that all the items in that batch are retried as a result.

While we initially implemented this as an error to reflect the full batch failure in the operational metrics (i.e. function runtime errors), there are cases such as when processing small batches that this behaviour can skew the metrics due to higher chances of a full batch to fail.

To accommodate these use cases, as well as those customers who simply want to avoid throwing an error, we should add a new policy `RaiseOnBatchFailure` (or similar) option to the utility that allows customers to opt out of the error throwing mechanism.

More information here: https://github.com/aws-powertools/powertools-lambda-typescript/issues/2122#issuecomment-1959176961

### Solution/User Experience

```csharp
public class CustomSqsRecordHandler : ISqsRecordHandler 
{
    public async Task<RecordHandlerResult> HandleAsync(SQSEvent.SQSMessage record, CancellationToken cancellationToken)
    {
         var product = JsonSerializer.Deserialize<Product>(record.Body);
         return await Task.FromResult(RecordHandlerResult.None); 
     }
}


[BatchProcessor(RecordHandler = typeof(CustomSqsRecordHandler), 
ErrorHandlingPolicy = BatchProcessorErrorHandlingPolicy.RaiseOnBatchFailure)]
public BatchItemFailuresResponse HandlerUsingAttribute(SQSEvent _)
{
    return SqsBatchProcessor.Result.BatchItemFailuresResponse; 
}
```

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (.NET) Tenets](https://docs.powertools.aws.dev/lambda/dotnet/tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/)

**Comment by lachriz-aws** [comment]
I'm happy to take a look at this. Will try to set time aside in the comings weeks.

**Comment by hjgraca** [comment]
thank you @lachriz-aws

**Comment by lachriz-aws** [comment]
Hi @hjgraca, I have now submitted a PR draft with a proposed solution to this, see https://github.com/aws-powertools/powertools-lambda-dotnet/pull/646 - let me know what you think.

I'm of course happy to update the docs as well (but wanted to wait until we have agreed on how the final solution should look like).

**Comment by hjgraca** [comment]
Release 1.15
