### ISSUE TITLE
Feature request: Enable Logging utility globally without decorator

### ISSUE THREAD

**Issue by CarlosGaleana** [aws-powertools/powertools-lambda-dotnet#669]
### Use case

I have a function with 10 handlers and I want to enable logging for incoming events, however I need to add the [Logging] decorator for each handler, and I would like to enable this utility globally without manually adding the decorator for each one.

### Solution/User Experience

Enable logging incoming event globally, setting an environment variable as: POWERTOOLS_LOGGER_LOG_EVENT without the [Logging] decorator for each handler.

### Acknowledgment

- [x] This feature request meets [Powertools for AWS Lambda (.NET) Tenets](https://docs.powertools.aws.dev/lambda/dotnet/tenets)
- [x] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/)

**Comment by hjgraca** [comment]
Hi @CarlosGaleana,
Thank you for opening this issue. After careful consideration and testing, we have decided not to implement this functionality in Powertools.

`POWERTOOLS_LOGGER_LOG_EVENT` instructs all [Logging] attributes to Log or not the event, this and other env variables allows you to configure the [Logging] attribute without code, but you still need to have [Logging] on each Lambda Function you want to log that event.

The current method-level restriction for the [Logging] attribute exists for several technical and performance reasons:

Scope and Performance:

Enabling assembly or module-level logging would apply the logging aspect to every method in the assembly
This would have significant performance implications as the aspect would be invoked on every method call
Even with filtering for [LambdaFunction] methods, we'd still incur the overhead of checking each method invocation


Technical Limitations:

While we could limit logging to methods with [LambdaFunction], this creates additional complexity and potential edge cases
The current method-level approach ensures precise control and optimal performance



Recommended Alternatives:

Continue using method-level [Logging] attribute alongside [LambdaFunction]. This maintains consistency as you're already explicitly marking Lambda methods.
To reduce repetition, you can:

Create IDE snippets for quick insertion of both attributes
Use your IDE's multi-cursor features to add attributes efficiently
Create a simple source generator if you need automation (This will involve even more code)


We appreciate your feedback and will continue to look for ways to improve the developer experience while maintaining performance and reliability.
